### ISSUE TITLE
different validation behaviour between azure and local docker containter

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox-ch-elm#2]
1Doc-NeisseriaGonorrhoeae.json

- The value provided ('de-CH') could not be validated because the code system urn:ietf:bcp:47 is not known
- Unable to check whether the code is in the value set [http://hl7.org/fhir/ValueSet/doc-typecodes|4.0.1](http://hl7.org/fhir/ValueSet/doc-typecodes%7C4.0.1)
- Unable to check whether the code is in the value set [http://fhir.ch/ig/ch-elm/ValueSet/ch-elm-lab-study-types|1.0.0](http://fhir.ch/ig/ch-elm/ValueSet/ch-elm-lab-study-types%7C1.0.0)
- Unable to check whether the code is in the value set [http://hl7.eu/fhir/laboratory/ValueSet/lab-reportType-eu-lab|current](http://hl7.eu/fhir/laboratory/ValueSet/lab-reportType-eu-lab%7Ccurrent)
- Constraint failed: ch-addr-1: 'ISO Country Alpha-2 or ISO Country Alpha-3 code' (defined in http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-address

2Doc-ChlamydiaTrachomatis.json
Constraint failed: ch-elm-material: 'Material declared by Observation.code or non-mandatory.' (defined in http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-observation-results-laboratory)

**Comment by qligier** [comment]
To debug the terminology server:
```yml
logging:
  level:
    ch.ahdis.matchbox.terminology: DEBUG
```

Not sure if we should increase log level for other packages.

**Comment by oliveregger** [comment]
this behaviour was triggered because the terminology server was not available on this port

**Comment by oliveregger** [comment]
should be fixed with release 1.0.4
