### ISSUE TITLE
Code Scanning alert

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox-ch-elm#5]
![image](https://github.com/ahdis/matchbox-ch-elm/assets/2414516/77825689-4d5e-4371-9a55-e417345721f4)

**Comment by qligier** [comment]
Already fixed in Matchbox: https://github.com/ahdis/matchbox/security/dependabot/105

**Comment by qligier** [comment]
I've fixed the scanner. For some reason, scanning the Dockerfile didn't scan the base image.
I've changed the scan to docker image mode, scanning the image that is used as base in this Dockerfile.
We also have a medium issue in Tomcat, also already fixed in Matchbox.
